// <auto-generated />
using System;
using ECommBackend.DatabaseConns;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ECommBackend.Migrations
{
    [DbContext(typeof(SQLiteConn))]
    partial class SQLiteConnModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ECommBackend.Models.AdminModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("ECommBackend.Models.ImageModel", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("BytesArray")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("BytesSize")
                        .HasColumnType("INTEGER");

                    b.HasKey("ImageId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("ECommBackend.Models.OrderModel", b =>
                {
                    b.Property<Guid>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OrderCreatorId")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("INTEGER");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("REAL");

                    b.HasKey("OrderId");

                    b.HasIndex("OrderCreatorId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ECommBackend.Models.ProductModel", b =>
                {
                    b.Property<Guid>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdminOwnerId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Base_SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key_Ingr")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Skin_Type")
                        .HasColumnType("TEXT");

                    b.Property<string>("Texture")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdateAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserModelUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.HasIndex("Base_SKU")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("UserModelUserId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("ECommBackend.Models.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ECommBackend.Models.VariantModel", b =>
                {
                    b.Property<Guid>("VariantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductModelId")
                        .HasColumnType("TEXT");

                    b.Property<double>("Size")
                        .HasColumnType("REAL");

                    b.Property<int>("Units")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("VariantImageId")
                        .HasColumnType("TEXT");

                    b.HasKey("VariantId");

                    b.HasIndex("Price")
                        .IsUnique();

                    b.HasIndex("ProductModelId");

                    b.HasIndex("Size")
                        .IsUnique();

                    b.HasIndex("VariantId")
                        .IsUnique();

                    b.HasIndex("VariantImageId")
                        .IsUnique();

                    b.ToTable("Variants");
                });

            modelBuilder.Entity("OrderProducts", b =>
                {
                    b.Property<Guid>("OrderModelOrderId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProductsProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderModelOrderId", "ProductsProductId");

                    b.HasIndex("ProductsProductId");

                    b.ToTable("OrderProducts");
                });

            modelBuilder.Entity("ECommBackend.Models.OrderModel", b =>
                {
                    b.HasOne("ECommBackend.Models.UserModel", "OrderCreator")
                        .WithMany("Orders")
                        .HasForeignKey("OrderCreatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderCreator");
                });

            modelBuilder.Entity("ECommBackend.Models.ProductModel", b =>
                {
                    b.HasOne("ECommBackend.Models.AdminModel", "Owner")
                        .WithMany("ProductsOwned")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ECommBackend.Models.UserModel", null)
                        .WithMany("ProductsBought")
                        .HasForeignKey("UserModelUserId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("ECommBackend.Models.VariantModel", b =>
                {
                    b.HasOne("ECommBackend.Models.ProductModel", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommBackend.Models.ImageModel", "VariantImage")
                        .WithOne()
                        .HasForeignKey("ECommBackend.Models.VariantModel", "VariantImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("VariantImage");
                });

            modelBuilder.Entity("OrderProducts", b =>
                {
                    b.HasOne("ECommBackend.Models.OrderModel", null)
                        .WithMany()
                        .HasForeignKey("OrderModelOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ECommBackend.Models.ProductModel", null)
                        .WithMany()
                        .HasForeignKey("ProductsProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ECommBackend.Models.AdminModel", b =>
                {
                    b.Navigation("ProductsOwned");
                });

            modelBuilder.Entity("ECommBackend.Models.ProductModel", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ECommBackend.Models.UserModel", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("ProductsBought");
                });
#pragma warning restore 612, 618
        }
    }
}
